apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: tensorflow-from-uri
spec:
  default:
    predictor:
      onnx:
        storageUri: https://github.com/tduffy000/kfserving-uri-examples/blob/master/onnx/frozen/model.onnx?raw=true